/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 37.2.0 Fri Oct 28 15:47:12 2022.
 */

#include <string.h>

#include "x8578_can_db_client.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int x8578_can_db_client_epic_pmz_k_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_k_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 48u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 40u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 32u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->bisg_calibration_id02, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u64(src_p->bisg_calibration_id02, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_k_unpack(
    struct x8578_can_db_client_epic_pmz_k_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bisg_calibration_id02 = unpack_left_shift_u64(src_p[0], 48u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_left_shift_u64(src_p[1], 40u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_left_shift_u64(src_p[2], 32u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_left_shift_u64(src_p[4], 16u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_left_shift_u64(src_p[5], 8u, 0xffu);
    dst_p->bisg_calibration_id02 |= unpack_right_shift_u64(src_p[6], 0u, 0xffu);

    return (0);
}

uint64_t x8578_can_db_client_epic_pmz_k_bisg_calibration_id02_encode(double value)
{
    return (uint64_t)(value);
}

double x8578_can_db_client_epic_pmz_k_bisg_calibration_id02_decode(uint64_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_k_bisg_calibration_id02_is_in_range(uint64_t value)
{
    return (value <= 72057594037927900ull);
}

int x8578_can_db_client_epic_pmz_l_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_l_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u32(src_p->bisg_calib_verif_number, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->bisg_calib_verif_number, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->bisg_calib_verif_number, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->bisg_calib_verif_number, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_l_unpack(
    struct x8578_can_db_client_epic_pmz_l_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bisg_calib_verif_number = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->bisg_calib_verif_number |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->bisg_calib_verif_number |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->bisg_calib_verif_number |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);

    return (0);
}

uint32_t x8578_can_db_client_epic_pmz_l_bisg_calib_verif_number_encode(double value)
{
    return (uint32_t)(value);
}

double x8578_can_db_client_epic_pmz_l_bisg_calib_verif_number_decode(uint32_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_l_bisg_calib_verif_number_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_epic_pmz_j_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_j_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 48u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 40u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 32u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 16u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->bisg_calibration_id01, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u64(src_p->bisg_calibration_id01, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_j_unpack(
    struct x8578_can_db_client_epic_pmz_j_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bisg_calibration_id01 = unpack_left_shift_u64(src_p[0], 48u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_left_shift_u64(src_p[1], 40u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_left_shift_u64(src_p[2], 32u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_left_shift_u64(src_p[4], 16u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_left_shift_u64(src_p[5], 8u, 0xffu);
    dst_p->bisg_calibration_id01 |= unpack_right_shift_u64(src_p[6], 0u, 0xffu);

    return (0);
}

uint64_t x8578_can_db_client_epic_pmz_j_bisg_calibration_id01_encode(double value)
{
    return (uint64_t)(value);
}

double x8578_can_db_client_epic_pmz_j_bisg_calibration_id01_decode(uint64_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_j_bisg_calibration_id01_is_in_range(uint64_t value)
{
    return (value <= 72057594037927900ull);
}

int x8578_can_db_client_epic_pmz_i_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_i_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u32(src_p->bisg_diagnostic01, 24u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->bisg_diagnostic01, 16u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->bisg_diagnostic01, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->bisg_diagnostic01, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_i_unpack(
    struct x8578_can_db_client_epic_pmz_i_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bisg_diagnostic01 = unpack_left_shift_u32(src_p[0], 24u, 0xffu);
    dst_p->bisg_diagnostic01 |= unpack_left_shift_u32(src_p[1], 16u, 0xffu);
    dst_p->bisg_diagnostic01 |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->bisg_diagnostic01 |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);

    return (0);
}

uint32_t x8578_can_db_client_epic_pmz_i_bisg_diagnostic01_encode(double value)
{
    return (uint32_t)(value);
}

double x8578_can_db_client_epic_pmz_i_bisg_diagnostic01_decode(uint32_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_i_bisg_diagnostic01_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_pcm_pmz_v_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_v_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->engine_torq_act_qf, 2u, 0x0cu);
    dst_p[1] |= pack_left_shift_u8(src_p->k0_mode_request, 0u, 0x03u);
    dst_p[2] |= pack_left_shift_u8(src_p->engine_start_torque, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->drvline_damp_enbl_flg_md1, 7u, 0x80u);
    dst_p[3] |= pack_left_shift_u8(src_p->engine_torq_counter, 3u, 0x78u);
    dst_p[3] |= pack_right_shift_u16(src_p->engine_torq_act, 8u, 0x07u);
    dst_p[4] |= pack_left_shift_u16(src_p->engine_torq_act, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->engine_torq_checksum, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->slip_start_type_request, 3u, 0xf8u);
    dst_p[6] |= pack_right_shift_u16(src_p->engine_torq_tgt_wo_trans, 8u, 0x07u);
    dst_p[7] |= pack_left_shift_u16(src_p->engine_torq_tgt_wo_trans, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_v_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_v_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->engine_torq_act_qf = unpack_right_shift_u8(src_p[1], 2u, 0x0cu);
    dst_p->k0_mode_request = unpack_right_shift_u8(src_p[1], 0u, 0x03u);
    dst_p->engine_start_torque = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->drvline_damp_enbl_flg_md1 = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->engine_torq_counter = unpack_right_shift_u8(src_p[3], 3u, 0x78u);
    dst_p->engine_torq_act = unpack_left_shift_u16(src_p[3], 8u, 0x07u);
    dst_p->engine_torq_act |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->engine_torq_checksum = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->slip_start_type_request = unpack_right_shift_u8(src_p[6], 3u, 0xf8u);
    dst_p->engine_torq_tgt_wo_trans = unpack_left_shift_u16(src_p[6], 8u, 0x07u);
    dst_p->engine_torq_tgt_wo_trans |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_qf_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_qf_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_qf_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_k0_mode_request_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_k0_mode_request_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_k0_mode_request_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_engine_start_torque_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_start_torque_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_start_torque_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_drvline_damp_enbl_flg_md1_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_drvline_damp_enbl_flg_md1_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_drvline_damp_enbl_flg_md1_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_encode(double value)
{
    return (uint16_t)(value - -1023.0);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_decode(uint16_t value)
{
    return ((double)value + -1023.0);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_act_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_checksum_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_checksum_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_checksum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_pcm_pmz_v_mhev_slip_start_type_request_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_v_mhev_slip_start_type_request_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_slip_start_type_request_is_in_range(uint8_t value)
{
    return ((value >= 17u) && (value <= 30u));
}

uint16_t x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_tgt_wo_trans_encode(double value)
{
    return (uint16_t)(value - -1023.0);
}

double x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_tgt_wo_trans_decode(uint16_t value)
{
    return ((double)value + -1023.0);
}

bool x8578_can_db_client_pcm_pmz_v_mhev_engine_torq_tgt_wo_trans_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

int x8578_can_db_client_epic_pmz_a_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->inverter_temperature, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->inverter_hvil_status, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u8(src_p->inv_active_short_circuit, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->epic_pump_diag_status, 3u, 0x08u);
    dst_p[2] |= pack_left_shift_u8(src_p->epic_chrg_em_pump_diag_stat, 2u, 0x04u);
    dst_p[2] |= pack_right_shift_u16(src_p->em_voltage_dc_link, 8u, 0x03u);
    dst_p[3] |= pack_left_shift_u16(src_p->em_voltage_dc_link, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->em_operating_mode_ext, 0u, 0x0fu);
    dst_p[5] |= pack_left_shift_u8(src_p->em_op_mode_ext_gp_counter, 4u, 0xf0u);
    dst_p[5] |= pack_left_shift_u8(src_p->emacoc_monitor_status, 3u, 0x08u);
    dst_p[5] |= pack_left_shift_u8(src_p->rapid_dschrg_diag_status, 2u, 0x04u);
    dst_p[5] |= pack_right_shift_u16(src_p->em_voltage_dc_link_ext, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->em_voltage_dc_link_ext, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->em_op_mode_ext_gp_cs, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_a_unpack(
    struct x8578_can_db_client_epic_pmz_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->inverter_temperature = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->inverter_hvil_status = unpack_right_shift_u8(src_p[1], 6u, 0xc0u);
    dst_p->inv_active_short_circuit = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->epic_pump_diag_status = unpack_right_shift_u8(src_p[2], 3u, 0x08u);
    dst_p->epic_chrg_em_pump_diag_stat = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->em_voltage_dc_link = unpack_left_shift_u16(src_p[2], 8u, 0x03u);
    dst_p->em_voltage_dc_link |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->em_operating_mode_ext = unpack_right_shift_u8(src_p[4], 0u, 0x0fu);
    dst_p->em_op_mode_ext_gp_counter = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->emacoc_monitor_status = unpack_right_shift_u8(src_p[5], 3u, 0x08u);
    dst_p->rapid_dschrg_diag_status = unpack_right_shift_u8(src_p[5], 2u, 0x04u);
    dst_p->em_voltage_dc_link_ext = unpack_left_shift_u16(src_p[5], 8u, 0x03u);
    dst_p->em_voltage_dc_link_ext |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->em_op_mode_ext_gp_cs = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_epic_pmz_a_inverter_temperature_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double x8578_can_db_client_epic_pmz_a_inverter_temperature_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool x8578_can_db_client_epic_pmz_a_inverter_temperature_is_in_range(uint8_t value)
{
    return (value <= 253u);
}

uint8_t x8578_can_db_client_epic_pmz_a_inverter_hvil_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_inverter_hvil_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_inverter_hvil_status_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t x8578_can_db_client_epic_pmz_a_inv_active_short_circuit_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_inv_active_short_circuit_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_inv_active_short_circuit_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_a_epic_pump_diag_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_epic_pump_diag_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_epic_pump_diag_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_a_epic_chrg_em_pump_diag_stat_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_epic_chrg_em_pump_diag_stat_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_epic_chrg_em_pump_diag_stat_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

uint8_t x8578_can_db_client_epic_pmz_a_em_operating_mode_ext_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_em_operating_mode_ext_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_em_operating_mode_ext_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t x8578_can_db_client_epic_pmz_a_emacoc_monitor_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_emacoc_monitor_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_emacoc_monitor_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_a_rapid_dschrg_diag_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_rapid_dschrg_diag_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_rapid_dschrg_diag_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_ext_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_ext_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_em_voltage_dc_link_ext_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_a_em_op_mode_ext_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_epic_pmz_c_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_c_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->em_speed_qf, 0u, 0x03u);
    dst_p[1] |= pack_left_shift_u8(src_p->em_torq_speed_ext_gp_counter, 3u, 0x78u);
    dst_p[1] |= pack_right_shift_u16(src_p->drvline_damp_torque_delta, 8u, 0x07u);
    dst_p[2] |= pack_left_shift_u16(src_p->drvline_damp_torque_delta, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->em_speed, 8u, 0x7fu);
    dst_p[4] |= pack_left_shift_u16(src_p->em_speed, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->em_torq_speed_ext_gp_cs, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->em_torque_ext, 8u, 0x7fu);
    dst_p[7] |= pack_left_shift_u16(src_p->em_torque_ext, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_c_unpack(
    struct x8578_can_db_client_epic_pmz_c_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_speed_qf = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->em_torq_speed_ext_gp_counter = unpack_right_shift_u8(src_p[1], 3u, 0x78u);
    dst_p->drvline_damp_torque_delta = unpack_left_shift_u16(src_p[1], 8u, 0x07u);
    dst_p->drvline_damp_torque_delta |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->em_speed = unpack_left_shift_u16(src_p[3], 8u, 0x7fu);
    dst_p->em_speed |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->em_torq_speed_ext_gp_cs = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->em_torque_ext = unpack_left_shift_u16(src_p[6], 8u, 0x7fu);
    dst_p->em_torque_ext |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_epic_pmz_c_em_speed_qf_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_c_em_speed_qf_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_c_em_speed_qf_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_epic_pmz_c_drvline_damp_torque_delta_encode(double value)
{
    return (uint16_t)((value - -102.3) / 0.1);
}

double x8578_can_db_client_epic_pmz_c_drvline_damp_torque_delta_decode(uint16_t value)
{
    return (((double)value * 0.1) + -102.3);
}

bool x8578_can_db_client_epic_pmz_c_drvline_damp_torque_delta_is_in_range(uint16_t value)
{
    return (value <= 2047u);
}

uint16_t x8578_can_db_client_epic_pmz_c_em_speed_encode(double value)
{
    return (uint16_t)(value - -16382.0);
}

double x8578_can_db_client_epic_pmz_c_em_speed_decode(uint16_t value)
{
    return ((double)value + -16382.0);
}

bool x8578_can_db_client_epic_pmz_c_em_speed_is_in_range(uint16_t value)
{
    return (value <= 32765u);
}

uint8_t x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_c_em_torq_speed_ext_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t x8578_can_db_client_epic_pmz_c_em_torque_ext_encode(double value)
{
    return (uint16_t)((value - -1638.3) / 0.1);
}

double x8578_can_db_client_epic_pmz_c_em_torque_ext_decode(uint16_t value)
{
    return (((double)value * 0.1) + -1638.3);
}

bool x8578_can_db_client_epic_pmz_c_em_torque_ext_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

int x8578_can_db_client_epic_pmz_e_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_e_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->em_current_dc_link, 8u, 0x0fu);
    dst_p[1] |= pack_left_shift_u16(src_p->em_current_dc_link, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->toc_pump_diag_status, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_start_current_derate, 6u, 0x40u);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_short_time_cur_derate, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u8(src_p->epicmil_request, 3u, 0x18u);
    dst_p[2] |= pack_left_shift_u8(src_p->em_pump_diag_status, 2u, 0x04u);
    dst_p[2] |= pack_left_shift_u8(src_p->inv_temperature_derate, 1u, 0x02u);
    dst_p[2] |= pack_right_shift_u16(src_p->em_temperature, 8u, 0x01u);
    dst_p[3] |= pack_left_shift_u16(src_p->em_temperature, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->em_rotor_temperature, 8u, 0x01u);
    dst_p[5] |= pack_left_shift_u16(src_p->em_rotor_temperature, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->temperature_rate, 0u, 0x7fu);

    return (8);
}

int x8578_can_db_client_epic_pmz_e_unpack(
    struct x8578_can_db_client_epic_pmz_e_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_current_dc_link = unpack_left_shift_u16(src_p[0], 8u, 0x0fu);
    dst_p->em_current_dc_link |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->toc_pump_diag_status = unpack_right_shift_u8(src_p[2], 7u, 0x80u);
    dst_p->inv_start_current_derate = unpack_right_shift_u8(src_p[2], 6u, 0x40u);
    dst_p->inv_short_time_cur_derate = unpack_right_shift_u8(src_p[2], 5u, 0x20u);
    dst_p->epicmil_request = unpack_right_shift_u8(src_p[2], 3u, 0x18u);
    dst_p->em_pump_diag_status = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->inv_temperature_derate = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->em_temperature = unpack_left_shift_u16(src_p[2], 8u, 0x01u);
    dst_p->em_temperature |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->em_rotor_temperature = unpack_left_shift_u16(src_p[4], 8u, 0x01u);
    dst_p->em_rotor_temperature |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->temperature_rate = unpack_right_shift_u8(src_p[6], 0u, 0x7fu);

    return (0);
}

uint16_t x8578_can_db_client_epic_pmz_e_em_current_dc_link_encode(double value)
{
    return (uint16_t)((value - -511.5) / 0.25);
}

double x8578_can_db_client_epic_pmz_e_em_current_dc_link_decode(uint16_t value)
{
    return (((double)value * 0.25) + -511.5);
}

bool x8578_can_db_client_epic_pmz_e_em_current_dc_link_is_in_range(uint16_t value)
{
    return (value <= 4093u);
}

uint8_t x8578_can_db_client_epic_pmz_e_toc_pump_diag_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_toc_pump_diag_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_toc_pump_diag_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_e_inv_start_current_derate_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_inv_start_current_derate_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_inv_start_current_derate_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_e_inv_short_time_cur_derate_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_inv_short_time_cur_derate_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_inv_short_time_cur_derate_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_e_epicmil_request_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_epicmil_request_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_epicmil_request_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t x8578_can_db_client_epic_pmz_e_em_pump_diag_status_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_em_pump_diag_status_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_em_pump_diag_status_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_epic_pmz_e_inv_temperature_derate_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_inv_temperature_derate_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_inv_temperature_derate_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t x8578_can_db_client_epic_pmz_e_em_temperature_encode(double value)
{
    return (uint16_t)(value - -40.0);
}

double x8578_can_db_client_epic_pmz_e_em_temperature_decode(uint16_t value)
{
    return ((double)value + -40.0);
}

bool x8578_can_db_client_epic_pmz_e_em_temperature_is_in_range(uint16_t value)
{
    return (value <= 509u);
}

uint16_t x8578_can_db_client_epic_pmz_e_em_rotor_temperature_encode(double value)
{
    return (uint16_t)(value - -40.0);
}

double x8578_can_db_client_epic_pmz_e_em_rotor_temperature_decode(uint16_t value)
{
    return ((double)value + -40.0);
}

bool x8578_can_db_client_epic_pmz_e_em_rotor_temperature_is_in_range(uint16_t value)
{
    return (value <= 511u);
}

uint8_t x8578_can_db_client_epic_pmz_e_temperature_rate_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_e_temperature_rate_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_e_temperature_rate_is_in_range(uint8_t value)
{
    return (value <= 120u);
}

int x8578_can_db_client_epic_pmz_g_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_g_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->em_torq_limit_gp_cs, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->em_torq_limit_gp_counter, 0u, 0x0fu);
    dst_p[3] |= pack_right_shift_u16(src_p->em_min_torque_limit, 2u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->em_min_torque_limit, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(src_p->em_min_cont_torque_limit, 4u, 0x3fu);
    dst_p[5] |= pack_left_shift_u16(src_p->em_min_cont_torque_limit, 4u, 0xf0u);
    dst_p[5] |= pack_right_shift_u16(src_p->em_max_torque_limit, 6u, 0x0fu);
    dst_p[6] |= pack_left_shift_u16(src_p->em_max_torque_limit, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->em_max_cont_torque_limit, 8u, 0x03u);
    dst_p[7] |= pack_left_shift_u16(src_p->em_max_cont_torque_limit, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_g_unpack(
    struct x8578_can_db_client_epic_pmz_g_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_torq_limit_gp_cs = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->em_torq_limit_gp_counter = unpack_right_shift_u8(src_p[2], 0u, 0x0fu);
    dst_p->em_min_torque_limit = unpack_left_shift_u16(src_p[3], 2u, 0xffu);
    dst_p->em_min_torque_limit |= unpack_right_shift_u16(src_p[4], 6u, 0xc0u);
    dst_p->em_min_cont_torque_limit = unpack_left_shift_u16(src_p[4], 4u, 0x3fu);
    dst_p->em_min_cont_torque_limit |= unpack_right_shift_u16(src_p[5], 4u, 0xf0u);
    dst_p->em_max_torque_limit = unpack_left_shift_u16(src_p[5], 6u, 0x0fu);
    dst_p->em_max_torque_limit |= unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->em_max_cont_torque_limit = unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->em_max_cont_torque_limit |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_g_em_torq_limit_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_epic_pmz_g_em_min_torque_limit_encode(double value)
{
    return (uint16_t)(value - -1023.0);
}

double x8578_can_db_client_epic_pmz_g_em_min_torque_limit_decode(uint16_t value)
{
    return ((double)value + -1023.0);
}

bool x8578_can_db_client_epic_pmz_g_em_min_torque_limit_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t x8578_can_db_client_epic_pmz_g_em_min_cont_torque_limit_encode(double value)
{
    return (uint16_t)(value - -1023.0);
}

double x8578_can_db_client_epic_pmz_g_em_min_cont_torque_limit_decode(uint16_t value)
{
    return ((double)value + -1023.0);
}

bool x8578_can_db_client_epic_pmz_g_em_min_cont_torque_limit_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t x8578_can_db_client_epic_pmz_g_em_max_torque_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_epic_pmz_g_em_max_torque_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_g_em_max_torque_limit_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t x8578_can_db_client_epic_pmz_g_em_max_cont_torque_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_epic_pmz_g_em_max_cont_torque_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_g_em_max_cont_torque_limit_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int x8578_can_db_client_epic_pmz_h_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_epic_pmz_h_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_right_shift_u16(src_p->em_voltage_dc_link_mv, 8u, 0x03u);
    dst_p[3] |= pack_left_shift_u16(src_p->em_voltage_dc_link_mv, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->em_op_mode_mv_gp_cs, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->em_operating_mode_ext2, 4u, 0xf0u);
    dst_p[5] |= pack_left_shift_u8(src_p->em_op_mode_mv_gp_counter, 0u, 0x0fu);
    dst_p[6] |= pack_right_shift_u16(src_p->bisg_speed, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->bisg_speed, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_epic_pmz_h_unpack(
    struct x8578_can_db_client_epic_pmz_h_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_voltage_dc_link_mv = unpack_left_shift_u16(src_p[2], 8u, 0x03u);
    dst_p->em_voltage_dc_link_mv |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->em_op_mode_mv_gp_cs = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->em_operating_mode_ext2 = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
    dst_p->em_op_mode_mv_gp_counter = unpack_right_shift_u8(src_p[5], 0u, 0x0fu);
    dst_p->bisg_speed = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->bisg_speed |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint16_t x8578_can_db_client_epic_pmz_h_em_voltage_dc_link_mv_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double x8578_can_db_client_epic_pmz_h_em_voltage_dc_link_mv_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool x8578_can_db_client_epic_pmz_h_em_voltage_dc_link_mv_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_epic_pmz_h_em_operating_mode_ext2_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_h_em_operating_mode_ext2_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_h_em_operating_mode_ext2_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_epic_pmz_h_em_op_mode_mv_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_epic_pmz_h_bisg_speed_encode(double value)
{
    return (uint16_t)(value - -32767.0);
}

double x8578_can_db_client_epic_pmz_h_bisg_speed_decode(uint16_t value)
{
    return ((double)value + -32767.0);
}

bool x8578_can_db_client_epic_pmz_h_bisg_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_uds_diag_resp_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_uds_diag_resp_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dummy_signal = (uint8_t)src_p->dummy_signal;
    dst_p[0] |= pack_left_shift_u8(dummy_signal, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_uds_diag_resp_unpack(
    struct x8578_can_db_client_uds_diag_resp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    dummy_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dummy_signal = (int8_t)dummy_signal;

    return (0);
}

int8_t x8578_can_db_client_uds_diag_resp_dummy_signal_encode(double value)
{
    return (int8_t)(value);
}

double x8578_can_db_client_uds_diag_resp_dummy_signal_decode(int8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_uds_diag_resp_dummy_signal_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_bcm_pmz_a_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_bcm_pmz_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->car_mode_hs, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->car_mode_hs_ub, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u8(src_p->power_mode_ub, 1u, 0x02u);
    dst_p[5] |= pack_left_shift_u8(src_p->power_mode, 0u, 0x1fu);

    return (8);
}

int x8578_can_db_client_bcm_pmz_a_unpack(
    struct x8578_can_db_client_bcm_pmz_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->car_mode_hs = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->car_mode_hs_ub = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->power_mode_ub = unpack_right_shift_u8(src_p[4], 1u, 0x02u);
    dst_p->power_mode = unpack_right_shift_u8(src_p[5], 0u, 0x1fu);

    return (0);
}

uint8_t x8578_can_db_client_bcm_pmz_a_car_mode_hs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_bcm_pmz_a_car_mode_hs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_bcm_pmz_a_car_mode_hs_is_in_range(uint8_t value)
{
    return ((value >= 6u) && (value <= 15u));
}

uint8_t x8578_can_db_client_bcm_pmz_a_car_mode_hs_ub_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_bcm_pmz_a_car_mode_hs_ub_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_bcm_pmz_a_car_mode_hs_ub_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_bcm_pmz_a_power_mode_ub_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_bcm_pmz_a_power_mode_ub_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_bcm_pmz_a_power_mode_ub_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_bcm_pmz_a_power_mode_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_bcm_pmz_a_power_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_bcm_pmz_a_power_mode_is_in_range(uint8_t value)
{
    return ((value >= 10u) && (value <= 31u));
}

int x8578_can_db_client_gwm_pmz_h_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_gwm_pmz_h_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->crash_status_rcm, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->crash_status_rcm_ub, 5u, 0x20u);

    return (8);
}

int x8578_can_db_client_gwm_pmz_h_unpack(
    struct x8578_can_db_client_gwm_pmz_h_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->crash_status_rcm = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->crash_status_rcm_ub = unpack_right_shift_u8(src_p[1], 5u, 0x20u);

    return (0);
}

uint8_t x8578_can_db_client_gwm_pmz_h_crash_status_rcm_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_gwm_pmz_h_crash_status_rcm_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_gwm_pmz_h_crash_status_rcm_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_gwm_pmz_h_crash_status_rcm_ub_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_gwm_pmz_h_crash_status_rcm_ub_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_gwm_pmz_h_crash_status_rcm_ub_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int x8578_can_db_client_pcm_pmz_ac_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_ac_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[4] |= pack_right_shift_u16(src_p->em_voltage_dc_link_req_mv, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->em_voltage_dc_link_req_mv, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_ac_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_ac_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_voltage_dc_link_req_mv = unpack_left_shift_u16(src_p[4], 8u, 0x03u);
    dst_p->em_voltage_dc_link_req_mv |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

uint16_t x8578_can_db_client_pcm_pmz_ac_mhev_em_voltage_dc_link_req_mv_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double x8578_can_db_client_pcm_pmz_ac_mhev_em_voltage_dc_link_req_mv_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool x8578_can_db_client_pcm_pmz_ac_mhev_em_voltage_dc_link_req_mv_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int x8578_can_db_client_pcm_pmz_f_hybrid_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_f_hybrid_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->vscem_req_gp_cs, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->vscem_req_gp_counter, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->em_operating_mode_req_ext, 0u, 0x0fu);
    dst_p[2] |= pack_right_shift_u16(src_p->em_voltage_dc_link_req_ext, 8u, 0x03u);
    dst_p[3] |= pack_left_shift_u16(src_p->em_voltage_dc_link_req_ext, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->em_speed_request_ext, 8u, 0x7fu);
    dst_p[5] |= pack_left_shift_u16(src_p->em_speed_request_ext, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->em_torque_request_ext, 8u, 0x7fu);
    dst_p[7] |= pack_left_shift_u16(src_p->em_torque_request_ext, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_f_hybrid_unpack(
    struct x8578_can_db_client_pcm_pmz_f_hybrid_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vscem_req_gp_cs = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->vscem_req_gp_counter = unpack_right_shift_u8(src_p[1], 4u, 0xf0u);
    dst_p->em_operating_mode_req_ext = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->em_voltage_dc_link_req_ext = unpack_left_shift_u16(src_p[2], 8u, 0x03u);
    dst_p->em_voltage_dc_link_req_ext |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->em_speed_request_ext = unpack_left_shift_u16(src_p[4], 8u, 0x7fu);
    dst_p->em_speed_request_ext |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->em_torque_request_ext = unpack_left_shift_u16(src_p[6], 8u, 0x7fu);
    dst_p->em_torque_request_ext |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_vscem_req_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t x8578_can_db_client_pcm_pmz_f_hybrid_em_operating_mode_req_ext_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_em_operating_mode_req_ext_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_em_operating_mode_req_ext_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_pcm_pmz_f_hybrid_em_voltage_dc_link_req_ext_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_em_voltage_dc_link_req_ext_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_em_voltage_dc_link_req_ext_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

uint16_t x8578_can_db_client_pcm_pmz_f_hybrid_em_speed_request_ext_encode(double value)
{
    return (uint16_t)(value - -16382.0);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_em_speed_request_ext_decode(uint16_t value)
{
    return ((double)value + -16382.0);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_em_speed_request_ext_is_in_range(uint16_t value)
{
    return (value <= 32765u);
}

uint16_t x8578_can_db_client_pcm_pmz_f_hybrid_em_torque_request_ext_encode(double value)
{
    return (uint16_t)((value - -1638.3) / 0.1);
}

double x8578_can_db_client_pcm_pmz_f_hybrid_em_torque_request_ext_decode(uint16_t value)
{
    return (((double)value * 0.1) + -1638.3);
}

bool x8578_can_db_client_pcm_pmz_f_hybrid_em_torque_request_ext_is_in_range(uint16_t value)
{
    return (value <= 32767u);
}

int x8578_can_db_client_pcm_pmz_t_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_t_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->toc_pump_dr_req, 0u, 0x7fu);
    dst_p[1] |= pack_left_shift_u8(src_p->em_coolant_pump_dr_req, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u16(src_p->em_cur_dc_link_gen_limit, 8u, 0x01u);
    dst_p[2] |= pack_left_shift_u16(src_p->em_cur_dc_link_gen_limit, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->em_gen_limit_grp_cs, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->em_gen_limit_grp_counter, 2u, 0x3cu);
    dst_p[4] |= pack_right_shift_u16(src_p->em_vol_dc_link_gen_limit, 8u, 0x03u);
    dst_p[5] |= pack_left_shift_u16(src_p->em_vol_dc_link_gen_limit, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_t_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_t_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->toc_pump_dr_req = unpack_right_shift_u8(src_p[0], 0u, 0x7fu);
    dst_p->em_coolant_pump_dr_req = unpack_right_shift_u8(src_p[1], 1u, 0xfeu);
    dst_p->em_cur_dc_link_gen_limit = unpack_left_shift_u16(src_p[1], 8u, 0x01u);
    dst_p->em_cur_dc_link_gen_limit |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->em_gen_limit_grp_cs = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->em_gen_limit_grp_counter = unpack_right_shift_u8(src_p[4], 2u, 0x3cu);
    dst_p->em_vol_dc_link_gen_limit = unpack_left_shift_u16(src_p[4], 8u, 0x03u);
    dst_p->em_vol_dc_link_gen_limit |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_t_mhev_toc_pump_dr_req_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_t_mhev_toc_pump_dr_req_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_toc_pump_dr_req_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint8_t x8578_can_db_client_pcm_pmz_t_mhev_em_coolant_pump_dr_req_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_t_mhev_em_coolant_pump_dr_req_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_em_coolant_pump_dr_req_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

uint16_t x8578_can_db_client_pcm_pmz_t_mhev_em_cur_dc_link_gen_limit_encode(double value)
{
    return (uint16_t)(value - -509.0);
}

double x8578_can_db_client_pcm_pmz_t_mhev_em_cur_dc_link_gen_limit_decode(uint16_t value)
{
    return ((double)value + -509.0);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_em_cur_dc_link_gen_limit_is_in_range(uint16_t value)
{
    return (value <= 509u);
}

uint8_t x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_em_gen_limit_grp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_pcm_pmz_t_mhev_em_vol_dc_link_gen_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_t_mhev_em_vol_dc_link_gen_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_t_mhev_em_vol_dc_link_gen_limit_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

int x8578_can_db_client_pcm_pmz_u_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_u_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[1] |= pack_left_shift_u8(src_p->vscem_torq_lim_gp_counter, 0u, 0x0fu);
    dst_p[2] |= pack_right_shift_u16(src_p->em_torque_min_limit, 2u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->em_torque_min_limit, 6u, 0xc0u);
    dst_p[3] |= pack_right_shift_u16(src_p->em_torque_max_limit, 4u, 0x3fu);
    dst_p[4] |= pack_left_shift_u16(src_p->em_torque_max_limit, 4u, 0xf0u);
    dst_p[4] |= pack_right_shift_u16(src_p->drvline_damp_torq_min_lim, 6u, 0x0fu);
    dst_p[5] |= pack_left_shift_u16(src_p->drvline_damp_torq_min_lim, 2u, 0xfcu);
    dst_p[5] |= pack_right_shift_u16(src_p->drvline_damp_torq_max_lim, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->drvline_damp_torq_max_lim, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->vscem_torq_lim_gp_cs, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_u_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_u_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->vscem_torq_lim_gp_counter = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->em_torque_min_limit = unpack_left_shift_u16(src_p[2], 2u, 0xffu);
    dst_p->em_torque_min_limit |= unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    dst_p->em_torque_max_limit = unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->em_torque_max_limit |= unpack_right_shift_u16(src_p[4], 4u, 0xf0u);
    dst_p->drvline_damp_torq_min_lim = unpack_left_shift_u16(src_p[4], 6u, 0x0fu);
    dst_p->drvline_damp_torq_min_lim |= unpack_right_shift_u16(src_p[5], 2u, 0xfcu);
    dst_p->drvline_damp_torq_max_lim = unpack_left_shift_u16(src_p[5], 8u, 0x03u);
    dst_p->drvline_damp_torq_max_lim |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->vscem_torq_lim_gp_cs = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_pcm_pmz_u_mhev_em_torque_min_limit_encode(double value)
{
    return (uint16_t)(value - -1021.0);
}

double x8578_can_db_client_pcm_pmz_u_mhev_em_torque_min_limit_decode(uint16_t value)
{
    return ((double)value + -1021.0);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_em_torque_min_limit_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

uint16_t x8578_can_db_client_pcm_pmz_u_mhev_em_torque_max_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_u_mhev_em_torque_max_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_em_torque_max_limit_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

uint16_t x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_min_lim_encode(double value)
{
    return (uint16_t)((value - -102.3) / 0.1);
}

double x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_min_lim_decode(uint16_t value)
{
    return (((double)value * 0.1) + -102.3);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_min_lim_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_max_lim_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_max_lim_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_drvline_damp_torq_max_lim_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_u_mhev_vscem_torq_lim_gp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_pcm_pmz_w_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_w_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->bisg_calibration_id_req, 7u, 0x80u);
    dst_p[0] |= pack_left_shift_u8(src_p->em_torque_gradient_pos, 0u, 0x7fu);
    dst_p[1] |= pack_right_shift_u16(src_p->engine_torque_ripple, 8u, 0x03u);
    dst_p[2] |= pack_left_shift_u16(src_p->engine_torque_ripple, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->em_motor_limit_grp_cs, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->em_torque_gradient_neg, 1u, 0xfeu);
    dst_p[4] |= pack_right_shift_u16(src_p->em_cur_dc_link_motor_limit, 8u, 0x01u);
    dst_p[5] |= pack_left_shift_u16(src_p->em_cur_dc_link_motor_limit, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->em_motor_limit_grp_counter, 2u, 0x3cu);
    dst_p[6] |= pack_right_shift_u16(src_p->em_vol_dc_link_motor_limit, 8u, 0x03u);
    dst_p[7] |= pack_left_shift_u16(src_p->em_vol_dc_link_motor_limit, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_w_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_w_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->bisg_calibration_id_req = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->em_torque_gradient_pos = unpack_right_shift_u8(src_p[0], 0u, 0x7fu);
    dst_p->engine_torque_ripple = unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->engine_torque_ripple |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->em_motor_limit_grp_cs = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->em_torque_gradient_neg = unpack_right_shift_u8(src_p[4], 1u, 0xfeu);
    dst_p->em_cur_dc_link_motor_limit = unpack_left_shift_u16(src_p[4], 8u, 0x01u);
    dst_p->em_cur_dc_link_motor_limit |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->em_motor_limit_grp_counter = unpack_right_shift_u8(src_p[6], 2u, 0x3cu);
    dst_p->em_vol_dc_link_motor_limit = unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->em_vol_dc_link_motor_limit |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_w_mhev_bisg_calibration_id_req_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_bisg_calibration_id_req_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_bisg_calibration_id_req_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_pos_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_pos_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_pos_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint16_t x8578_can_db_client_pcm_pmz_w_mhev_engine_torque_ripple_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_engine_torque_ripple_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_engine_torque_ripple_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint8_t x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_cs_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_cs_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_cs_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_neg_encode(double value)
{
    return (uint8_t)(value / -10.0);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_neg_decode(uint8_t value)
{
    return ((double)value * -10.0);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_torque_gradient_neg_is_in_range(uint8_t value)
{
    return ((value >= 127u) && (value <= 0u));
}

uint16_t x8578_can_db_client_pcm_pmz_w_mhev_em_cur_dc_link_motor_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_cur_dc_link_motor_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_cur_dc_link_motor_limit_is_in_range(uint16_t value)
{
    return (value <= 509u);
}

uint8_t x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_counter_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_counter_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_motor_limit_grp_counter_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint16_t x8578_can_db_client_pcm_pmz_w_mhev_em_vol_dc_link_motor_limit_encode(double value)
{
    return (uint16_t)(value);
}

double x8578_can_db_client_pcm_pmz_w_mhev_em_vol_dc_link_motor_limit_decode(uint16_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_pcm_pmz_w_mhev_em_vol_dc_link_motor_limit_is_in_range(uint16_t value)
{
    return (value <= 1021u);
}

int x8578_can_db_client_pcm_pmz_x_mhev_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_pcm_pmz_x_mhev_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[2] |= pack_left_shift_u8(src_p->em_end_speed_esa, 0u, 0x7fu);
    dst_p[4] |= pack_left_shift_u8(src_p->em_duration_max_esa, 2u, 0x7cu);
    dst_p[6] |= pack_left_shift_u8(src_p->em_torque_limit_esa, 2u, 0xfcu);
    dst_p[6] |= pack_right_shift_u16(src_p->em_speed_gradient_esa, 8u, 0x03u);
    dst_p[7] |= pack_left_shift_u16(src_p->em_speed_gradient_esa, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_pcm_pmz_x_mhev_unpack(
    struct x8578_can_db_client_pcm_pmz_x_mhev_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->em_end_speed_esa = unpack_right_shift_u8(src_p[2], 0u, 0x7fu);
    dst_p->em_duration_max_esa = unpack_right_shift_u8(src_p[4], 2u, 0x7cu);
    dst_p->em_torque_limit_esa = unpack_right_shift_u8(src_p[6], 2u, 0xfcu);
    dst_p->em_speed_gradient_esa = unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->em_speed_gradient_esa |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

uint8_t x8578_can_db_client_pcm_pmz_x_mhev_em_end_speed_esa_encode(double value)
{
    return (uint8_t)(value / 10.0);
}

double x8578_can_db_client_pcm_pmz_x_mhev_em_end_speed_esa_decode(uint8_t value)
{
    return ((double)value * 10.0);
}

bool x8578_can_db_client_pcm_pmz_x_mhev_em_end_speed_esa_is_in_range(uint8_t value)
{
    return (value <= 127u);
}

uint8_t x8578_can_db_client_pcm_pmz_x_mhev_em_duration_max_esa_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double x8578_can_db_client_pcm_pmz_x_mhev_em_duration_max_esa_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool x8578_can_db_client_pcm_pmz_x_mhev_em_duration_max_esa_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t x8578_can_db_client_pcm_pmz_x_mhev_em_torque_limit_esa_encode(double value)
{
    return (uint8_t)(value / -1.0);
}

double x8578_can_db_client_pcm_pmz_x_mhev_em_torque_limit_esa_decode(uint8_t value)
{
    return ((double)value * -1.0);
}

bool x8578_can_db_client_pcm_pmz_x_mhev_em_torque_limit_esa_is_in_range(uint8_t value)
{
    return ((value >= 63u) && (value <= 0u));
}

uint16_t x8578_can_db_client_pcm_pmz_x_mhev_em_speed_gradient_esa_encode(double value)
{
    return (uint16_t)(value / -10.0);
}

double x8578_can_db_client_pcm_pmz_x_mhev_em_speed_gradient_esa_decode(uint16_t value)
{
    return ((double)value * -10.0);
}

bool x8578_can_db_client_pcm_pmz_x_mhev_em_speed_gradient_esa_is_in_range(uint16_t value)
{
    return ((value >= 1023u) && (value <= 0u));
}

int x8578_can_db_client_uds_diag_fun_req_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_uds_diag_fun_req_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dummy_signal = (uint8_t)src_p->dummy_signal;
    dst_p[0] |= pack_left_shift_u8(dummy_signal, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_uds_diag_fun_req_unpack(
    struct x8578_can_db_client_uds_diag_fun_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    dummy_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dummy_signal = (int8_t)dummy_signal;

    return (0);
}

int8_t x8578_can_db_client_uds_diag_fun_req_dummy_signal_encode(double value)
{
    return (int8_t)(value);
}

double x8578_can_db_client_uds_diag_fun_req_dummy_signal_decode(int8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_uds_diag_fun_req_dummy_signal_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_uds_diag_phy_req_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_uds_diag_phy_req_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dummy_signal = (uint8_t)src_p->dummy_signal;
    dst_p[0] |= pack_left_shift_u8(dummy_signal, 0u, 0xffu);

    return (8);
}

int x8578_can_db_client_uds_diag_phy_req_unpack(
    struct x8578_can_db_client_uds_diag_phy_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t dummy_signal;

    if (size < 8u) {
        return (-EINVAL);
    }

    dummy_signal = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dummy_signal = (int8_t)dummy_signal;

    return (0);
}

int8_t x8578_can_db_client_uds_diag_phy_req_dummy_signal_encode(double value)
{
    return (int8_t)(value);
}

double x8578_can_db_client_uds_diag_phy_req_dummy_signal_decode(int8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_uds_diag_phy_req_dummy_signal_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int x8578_can_db_client_vehconfig_400_pmz_auto_sar_pack(
    uint8_t *dst_p,
    const struct x8578_can_db_client_vehconfig_400_pmz_auto_sar_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->sf_vehconfig_400_pmz_auto_sar_pdu, 0u, 0xffu);

    switch (src_p->sf_vehconfig_400_pmz_auto_sar_pdu) {

    case 87:
        dst_p[4] |= pack_right_shift_u32(src_p->ccf_vin_part1, 24u, 0xffu);
        dst_p[5] |= pack_right_shift_u32(src_p->ccf_vin_part1, 16u, 0xffu);
        dst_p[6] |= pack_right_shift_u32(src_p->ccf_vin_part1, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u32(src_p->ccf_vin_part1, 0u, 0xffu);
        break;

    case 88:
        dst_p[1] |= pack_right_shift_u64(src_p->ccf_vin_part2, 48u, 0xffu);
        dst_p[2] |= pack_right_shift_u64(src_p->ccf_vin_part2, 40u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->ccf_vin_part2, 32u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->ccf_vin_part2, 24u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->ccf_vin_part2, 16u, 0xffu);
        dst_p[6] |= pack_right_shift_u64(src_p->ccf_vin_part2, 8u, 0xffu);
        dst_p[7] |= pack_left_shift_u64(src_p->ccf_vin_part2, 0u, 0xffu);
        break;

    case 89:
        dst_p[1] |= pack_right_shift_u64(src_p->ccf_vin_part3, 40u, 0xffu);
        dst_p[2] |= pack_right_shift_u64(src_p->ccf_vin_part3, 32u, 0xffu);
        dst_p[3] |= pack_right_shift_u64(src_p->ccf_vin_part3, 24u, 0xffu);
        dst_p[4] |= pack_right_shift_u64(src_p->ccf_vin_part3, 16u, 0xffu);
        dst_p[5] |= pack_right_shift_u64(src_p->ccf_vin_part3, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u64(src_p->ccf_vin_part3, 0u, 0xffu);
        break;

    case 97:
        dst_p[5] |= pack_left_shift_u8(src_p->ccf_mild_hybrid_type, 4u, 0xf0u);
        break;

    case 176:
        dst_p[1] |= pack_right_shift_u32(src_p->ccf_dd00_global_real_time, 24u, 0xffu);
        dst_p[2] |= pack_right_shift_u32(src_p->ccf_dd00_global_real_time, 16u, 0xffu);
        dst_p[3] |= pack_right_shift_u32(src_p->ccf_dd00_global_real_time, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u32(src_p->ccf_dd00_global_real_time, 0u, 0xffu);
        dst_p[5] |= pack_left_shift_u8(src_p->ccf_dd02_main_ecu_sup_volts, 0u, 0xffu);
        dst_p[6] |= pack_left_shift_u8(src_p->ccf_dd06_power_mode_pkt, 0u, 0x1fu);
        break;

    case 177:
        dst_p[1] |= pack_right_shift_u32(src_p->ccf_dd01_total_distance, 16u, 0xffu);
        dst_p[2] |= pack_right_shift_u32(src_p->ccf_dd01_total_distance, 8u, 0xffu);
        dst_p[3] |= pack_left_shift_u32(src_p->ccf_dd01_total_distance, 0u, 0xffu);
        dst_p[4] |= pack_left_shift_u8(src_p->ccf_dd04_in_car_temp, 0u, 0xffu);
        dst_p[5] |= pack_left_shift_u8(src_p->ccf_dd05_outdoor_temp, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int x8578_can_db_client_vehconfig_400_pmz_auto_sar_unpack(
    struct x8578_can_db_client_vehconfig_400_pmz_auto_sar_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sf_vehconfig_400_pmz_auto_sar_pdu = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->sf_vehconfig_400_pmz_auto_sar_pdu) {

    case 87:
        dst_p->ccf_vin_part1 = unpack_left_shift_u32(src_p[4], 24u, 0xffu);
        dst_p->ccf_vin_part1 |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
        dst_p->ccf_vin_part1 |= unpack_left_shift_u32(src_p[6], 8u, 0xffu);
        dst_p->ccf_vin_part1 |= unpack_right_shift_u32(src_p[7], 0u, 0xffu);
        break;

    case 88:
        dst_p->ccf_vin_part2 = unpack_left_shift_u64(src_p[1], 48u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_left_shift_u64(src_p[2], 40u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_left_shift_u64(src_p[3], 32u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_left_shift_u64(src_p[4], 24u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_left_shift_u64(src_p[5], 16u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_left_shift_u64(src_p[6], 8u, 0xffu);
        dst_p->ccf_vin_part2 |= unpack_right_shift_u64(src_p[7], 0u, 0xffu);
        break;

    case 89:
        dst_p->ccf_vin_part3 = unpack_left_shift_u64(src_p[1], 40u, 0xffu);
        dst_p->ccf_vin_part3 |= unpack_left_shift_u64(src_p[2], 32u, 0xffu);
        dst_p->ccf_vin_part3 |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
        dst_p->ccf_vin_part3 |= unpack_left_shift_u64(src_p[4], 16u, 0xffu);
        dst_p->ccf_vin_part3 |= unpack_left_shift_u64(src_p[5], 8u, 0xffu);
        dst_p->ccf_vin_part3 |= unpack_right_shift_u64(src_p[6], 0u, 0xffu);
        break;

    case 97:
        dst_p->ccf_mild_hybrid_type = unpack_right_shift_u8(src_p[5], 4u, 0xf0u);
        break;

    case 176:
        dst_p->ccf_dd00_global_real_time = unpack_left_shift_u32(src_p[1], 24u, 0xffu);
        dst_p->ccf_dd00_global_real_time |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
        dst_p->ccf_dd00_global_real_time |= unpack_left_shift_u32(src_p[3], 8u, 0xffu);
        dst_p->ccf_dd00_global_real_time |= unpack_right_shift_u32(src_p[4], 0u, 0xffu);
        dst_p->ccf_dd02_main_ecu_sup_volts = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
        dst_p->ccf_dd06_power_mode_pkt = unpack_right_shift_u8(src_p[6], 0u, 0x1fu);
        break;

    case 177:
        dst_p->ccf_dd01_total_distance = unpack_left_shift_u32(src_p[1], 16u, 0xffu);
        dst_p->ccf_dd01_total_distance |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
        dst_p->ccf_dd01_total_distance |= unpack_right_shift_u32(src_p[3], 0u, 0xffu);
        dst_p->ccf_dd04_in_car_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
        dst_p->ccf_dd05_outdoor_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
        break;

    default:
        break;
    }

    return (0);
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_sf_vehconfig_400_pmz_auto_sar_pdu_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_sf_vehconfig_400_pmz_auto_sar_pdu_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_sf_vehconfig_400_pmz_auto_sar_pdu_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint64_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part2_encode(double value)
{
    return (uint64_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part2_decode(uint64_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part2_is_in_range(uint64_t value)
{
    return (value <= 72057594037927900ull);
}

uint64_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part3_encode(double value)
{
    return (uint64_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part3_decode(uint64_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part3_is_in_range(uint64_t value)
{
    return (value <= 281474976710655ull);
}

uint32_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd00_global_real_time_encode(double value)
{
    return (uint32_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd00_global_real_time_decode(uint32_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd00_global_real_time_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd01_total_distance_encode(double value)
{
    return (uint32_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd01_total_distance_decode(uint32_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd01_total_distance_is_in_range(uint32_t value)
{
    return (value <= 16777215u);
}

uint32_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part1_encode(double value)
{
    return (uint32_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part1_decode(uint32_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_vin_part1_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd04_in_car_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd04_in_car_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd04_in_car_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_mild_hybrid_type_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_mild_hybrid_type_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_mild_hybrid_type_is_in_range(uint8_t value)
{
    return ((value >= 6u) && (value <= 14u));
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd02_main_ecu_sup_volts_encode(double value)
{
    return (uint8_t)(value / 0.25);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd02_main_ecu_sup_volts_decode(uint8_t value)
{
    return ((double)value * 0.25);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd02_main_ecu_sup_volts_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd05_outdoor_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd05_outdoor_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd05_outdoor_temp_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd06_power_mode_pkt_encode(double value)
{
    return (uint8_t)(value);
}

double x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd06_power_mode_pkt_decode(uint8_t value)
{
    return ((double)value);
}

bool x8578_can_db_client_vehconfig_400_pmz_auto_sar_ccf_dd06_power_mode_pkt_is_in_range(uint8_t value)
{
    return (value <= 31u);
}
