/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Thu Mar 28 23:42:29 2024.
 */

#include <string.h>

#include "bms_mc2.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int bms_mc2_bms_data_a_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_1_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_1_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_2_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_2_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_3_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_3_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_4_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_4_voltage, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_a_unpack(
    struct bms_mc2_bms_data_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_1_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_1_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_2_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_2_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_3_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_3_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell_4_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_4_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_a_init(struct bms_mc2_bms_data_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_a_t));

    return 0;
}

uint16_t bms_mc2_bms_data_a_cell_1_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_a_cell_1_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_a_cell_1_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_a_cell_2_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_a_cell_2_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_a_cell_2_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_a_cell_3_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_a_cell_3_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_a_cell_3_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_a_cell_4_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_a_cell_4_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_a_cell_4_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_b_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_b_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_5_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_5_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_6_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_6_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_7_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_7_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_8_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_8_voltage, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_b_unpack(
    struct bms_mc2_bms_data_b_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_5_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_5_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_6_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_6_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_7_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_7_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell_8_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_8_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_b_init(struct bms_mc2_bms_data_b_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_b_t));

    return 0;
}

uint16_t bms_mc2_bms_data_b_cell_5_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_b_cell_5_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_b_cell_5_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_b_cell_6_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_b_cell_6_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_b_cell_6_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_b_cell_7_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_b_cell_7_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_b_cell_7_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_b_cell_8_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_b_cell_8_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_b_cell_8_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_c_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_c_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_9_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_9_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_10_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_10_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_11_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_11_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_12_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_12_voltage, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_c_unpack(
    struct bms_mc2_bms_data_c_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_9_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_9_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_10_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_10_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_11_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_11_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell_12_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_12_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_c_init(struct bms_mc2_bms_data_c_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_c_t));

    return 0;
}

uint16_t bms_mc2_bms_data_c_cell_9_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_c_cell_9_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_c_cell_9_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_c_cell_10_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_c_cell_10_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_c_cell_10_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_c_cell_11_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_c_cell_11_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_c_cell_11_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_c_cell_12_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_c_cell_12_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_c_cell_12_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_d_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_d_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_13_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_13_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_14_voltage, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_14_voltage, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_15_voltage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_15_voltage, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_16_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_16_voltage, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_d_unpack(
    struct bms_mc2_bms_data_d_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_13_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_13_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_14_voltage = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_14_voltage |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_15_voltage = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_15_voltage |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell_16_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_16_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_d_init(struct bms_mc2_bms_data_d_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_d_t));

    return 0;
}

uint16_t bms_mc2_bms_data_d_cell_13_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_d_cell_13_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_d_cell_13_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_d_cell_14_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_d_cell_14_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_d_cell_14_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_d_cell_15_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_d_cell_15_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_d_cell_15_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_d_cell_16_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_d_cell_16_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_d_cell_16_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_e_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_e_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->temp1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->temp1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temp3, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temp3, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->temp4, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->temp4, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_e_unpack(
    struct bms_mc2_bms_data_e_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->temp1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->temp1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temp3 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temp3 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->temp4 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->temp4 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_e_init(struct bms_mc2_bms_data_e_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_e_t));

    return 0;
}

uint16_t bms_mc2_bms_data_e_temp1_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_e_temp1_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_e_temp1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_e_temp2_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_e_temp2_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_e_temp2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_e_temp3_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_e_temp3_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_e_temp3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_e_temp4_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_e_temp4_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_e_temp4_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_f_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_f_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->temp5, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->temp5, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp6, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp6, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temp7, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temp7, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->temp8, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->temp8, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_f_unpack(
    struct bms_mc2_bms_data_f_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->temp5 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->temp5 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp6 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp6 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temp7 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temp7 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->temp8 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->temp8 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_f_init(struct bms_mc2_bms_data_f_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_f_t));

    return 0;
}

uint16_t bms_mc2_bms_data_f_temp5_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_f_temp5_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_f_temp5_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_f_temp6_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_f_temp6_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_f_temp6_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_f_temp7_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_f_temp7_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_f_temp7_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t bms_mc2_bms_data_f_temp8_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_f_temp8_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_f_temp8_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_bms_data_g_pack(
    uint8_t *dst_p,
    const struct bms_mc2_bms_data_g_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->temp9, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->temp9, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->temp10, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->temp10, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->temp11, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->temp11, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->current, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->current, 8u, 0xffu);

    return (8);
}

int bms_mc2_bms_data_g_unpack(
    struct bms_mc2_bms_data_g_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->temp9 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->temp9 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->temp10 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->temp10 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->temp11 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->temp11 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->current = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->current |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int bms_mc2_bms_data_g_init(struct bms_mc2_bms_data_g_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_bms_data_g_t));

    return 0;
}

uint16_t bms_mc2_bms_data_g_temp9_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_g_temp9_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_g_temp9_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t bms_mc2_bms_data_g_temp10_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_g_temp10_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_g_temp10_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t bms_mc2_bms_data_g_temp11_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_g_temp11_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_g_temp11_is_in_range(uint16_t value)
{
    return (value <= 4095u);
}

uint16_t bms_mc2_bms_data_g_current_encode(double value)
{
    return (uint16_t)(value);
}

double bms_mc2_bms_data_g_current_decode(uint16_t value)
{
    return ((double)value);
}

bool bms_mc2_bms_data_g_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_config_data_command_pack(
    uint8_t *dst_p,
    const struct bms_mc2_config_data_command_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->calibration_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->store_changes_flag, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->update_value_flag, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->check_value_flag, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->value_index, 3u, 0xf8u);
    dst_p[2] |= pack_left_shift_u8(src_p->charger_present, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->request_balancing, 1u, 0x02u);
    dst_p[2] |= pack_left_shift_u8(src_p->request_report_now, 2u, 0x04u);
    dst_p[4] |= pack_left_shift_u32(src_p->raw_float, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->raw_float, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->raw_float, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->raw_float, 24u, 0xffu);

    return (8);
}

int bms_mc2_config_data_command_unpack(
    struct bms_mc2_config_data_command_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->calibration_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->store_changes_flag = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->update_value_flag = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->check_value_flag = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->value_index = unpack_right_shift_u8(src_p[1], 3u, 0xf8u);
    dst_p->charger_present = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->request_balancing = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->request_report_now = unpack_right_shift_u8(src_p[2], 2u, 0x04u);
    dst_p->raw_float = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int bms_mc2_config_data_command_init(struct bms_mc2_config_data_command_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_config_data_command_t));

    return 0;
}

uint8_t bms_mc2_config_data_command_calibration_id_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_calibration_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_calibration_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_mc2_config_data_command_store_changes_flag_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_store_changes_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_store_changes_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_command_update_value_flag_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_update_value_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_update_value_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_command_check_value_flag_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_check_value_flag_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_check_value_flag_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_command_value_index_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_value_index_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_value_index_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t bms_mc2_config_data_command_charger_present_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_charger_present_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_charger_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_command_request_balancing_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_request_balancing_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_request_balancing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_command_request_report_now_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_command_request_report_now_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_request_report_now_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t bms_mc2_config_data_command_raw_float_encode(double value)
{
    return (uint32_t)(value);
}

double bms_mc2_config_data_command_raw_float_decode(uint32_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_command_raw_float_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_config_data_response_pack(
    uint8_t *dst_p,
    const struct bms_mc2_config_data_response_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->calibration_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->unknown_id, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->update_success, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->store_success, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->value_index, 3u, 0xf8u);
    dst_p[2] |= pack_left_shift_u8(src_p->charging, 0u, 0x01u);
    dst_p[2] |= pack_left_shift_u8(src_p->balancing, 1u, 0x02u);
    dst_p[4] |= pack_left_shift_u32(src_p->raw_float, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->raw_float, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->raw_float, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->raw_float, 24u, 0xffu);

    return (8);
}

int bms_mc2_config_data_response_unpack(
    struct bms_mc2_config_data_response_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->calibration_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->unknown_id = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->update_success = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->store_success = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->value_index = unpack_right_shift_u8(src_p[1], 3u, 0xf8u);
    dst_p->charging = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->balancing = unpack_right_shift_u8(src_p[2], 1u, 0x02u);
    dst_p->raw_float = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->raw_float |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int bms_mc2_config_data_response_init(struct bms_mc2_config_data_response_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_config_data_response_t));

    return 0;
}

uint8_t bms_mc2_config_data_response_calibration_id_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_calibration_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_calibration_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t bms_mc2_config_data_response_unknown_id_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_unknown_id_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_unknown_id_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_response_update_success_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_update_success_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_update_success_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_response_store_success_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_store_success_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_store_success_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_response_value_index_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_value_index_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_value_index_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

uint8_t bms_mc2_config_data_response_charging_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_charging_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_charging_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_config_data_response_balancing_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_config_data_response_balancing_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_balancing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t bms_mc2_config_data_response_raw_float_encode(double value)
{
    return (uint32_t)(value);
}

double bms_mc2_config_data_response_raw_float_decode(uint32_t value)
{
    return ((double)value);
}

bool bms_mc2_config_data_response_raw_float_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int bms_mc2_urgent_status_pack(
    uint8_t *dst_p,
    const struct bms_mc2_urgent_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->not_configured, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->over_voltage, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->over_temp, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->over_discharge, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->under_voltage, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->under_temp, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->over_charge, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->lost_comms, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->out_of_balance, 0u, 0x01u);

    return (8);
}

int bms_mc2_urgent_status_unpack(
    struct bms_mc2_urgent_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->not_configured = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->over_voltage = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->over_temp = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->over_discharge = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->under_voltage = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->under_temp = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->over_charge = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->lost_comms = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->out_of_balance = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    return (0);
}

int bms_mc2_urgent_status_init(struct bms_mc2_urgent_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct bms_mc2_urgent_status_t));

    return 0;
}

uint8_t bms_mc2_urgent_status_not_configured_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_not_configured_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_not_configured_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_over_voltage_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_over_voltage_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_over_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_over_temp_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_over_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_over_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_over_discharge_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_over_discharge_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_over_discharge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_under_voltage_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_under_voltage_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_under_voltage_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_under_temp_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_under_temp_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_under_temp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_over_charge_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_over_charge_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_over_charge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_lost_comms_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_lost_comms_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_lost_comms_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t bms_mc2_urgent_status_out_of_balance_encode(double value)
{
    return (uint8_t)(value);
}

double bms_mc2_urgent_status_out_of_balance_decode(uint8_t value)
{
    return ((double)value);
}

bool bms_mc2_urgent_status_out_of_balance_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
