#ifndef CONTROLCONFIG
#define CONTROLCONFIG

#define PDGP_POWER_LIMIT 14000
#define POWER_LIMIT_MARGIN 500

#define CELL_MINIMUM_VOLTAGE 2.8
#define CELL_MAXIMUM_VOLTAGE 4.2
#define CELL_MAXIMUM_CURRENT 35
#define CELL_MAXIMUM_TEMP 60

#define PACK_CELLS_P 9
#define PACK_CELLS_S 13
#define PACK_MAXIMUM_TEMP CELL_MAXIMUM_TEMP
#define PACK_CURRENT_MAX PACK_CELLS_P*CELL_MAXIMUM_CURRENT
#define PACK_VOLTAGE_MIN PACK_CELLS_P*CELL_MINIMUM_VOLTAGE
#define PACK_VOLTAGE_MIN PACK_CELLS_P*CELL_MAXIMUM_VOLTAGE

#define STALE_DATA_THRESHOLD 50000
#define USEDCELLS 13


#endif