#ifndef IBSGCONFIG
#define IBSGCONFIG

#define PDGP_POWER_LIMIT 14000

#define U_MHEV_TORQ_MIN_LIMIT -55
#define U_MHEV_TORQ_MAX_LIMIT 55

#define W_MHEV_DC_CURR_LIMIT 350
#define W_MHEV_DC_VOLT_MIN 38
#define T_MHEV_REGEN_CURR_LIMIT -120
#define T_MHEV_REGEN_VOLT_LIMIT 54.6

#define U_MHEV_DMP_MIN_LIMIT -44
#define U_MHEV_DMP_MAX_LIMIT 44
#define W_MHEV_TORQUE_GRAD_POS 500
#define W_MHEV_TORQUE_GRAD_NEG -500

#endif