/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.5 Tue Sep  3 18:00:04 2024.
 */

#include <string.h>

#include "kms_dbc_real_time_part.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int kms_dbc_real_time_part_new_message_20_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_new_message_20_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[7] |= pack_left_shift_u8(src_p->new_signal_155, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_new_message_20_unpack(
    struct kms_dbc_real_time_part_new_message_20_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->new_signal_155 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_new_message_20_init(struct kms_dbc_real_time_part_new_message_20_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_new_message_20_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_new_message_20_new_signal_155_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_new_message_20_new_signal_155_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_new_message_20_new_signal_155_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_fault_code_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_fault_code_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fault_frame_id, 0u, 0xffu);

    switch (src_p->fault_frame_id) {

    case 1:
        dst_p[1] |= pack_left_shift_u8(src_p->cell_v_h, 0u, 0x07u);
        dst_p[1] |= pack_left_shift_u8(src_p->cell_v_l, 3u, 0x38u);
        dst_p[2] |= pack_left_shift_u8(src_p->detal_v_h, 0u, 0x07u);
        dst_p[2] |= pack_left_shift_u8(src_p->cell_t_chg_h, 3u, 0x38u);
        dst_p[3] |= pack_left_shift_u8(src_p->cell_t_chg_l, 0u, 0x07u);
        dst_p[3] |= pack_left_shift_u8(src_p->cell_t_dsg_h, 3u, 0x38u);
        dst_p[4] |= pack_left_shift_u8(src_p->cell_t_dsg_l, 0u, 0x07u);
        dst_p[4] |= pack_left_shift_u8(src_p->detal_t_h, 3u, 0x38u);
        dst_p[5] |= pack_left_shift_u8(src_p->sum_v_h, 0u, 0x07u);
        dst_p[5] |= pack_left_shift_u8(src_p->sum_v_l, 3u, 0x38u);
        dst_p[5] |= pack_left_shift_u8(src_p->short_protect, 6u, 0x40u);
        dst_p[6] |= pack_left_shift_u8(src_p->cur_chg_h, 0u, 0x07u);
        dst_p[6] |= pack_left_shift_u8(src_p->cur_dsg_h, 3u, 0x38u);
        dst_p[6] |= pack_left_shift_u8(src_p->afe_pf_det_st, 6u, 0x40u);
        dst_p[7] |= pack_left_shift_u8(src_p->soc_l, 0u, 0x07u);
        dst_p[7] |= pack_left_shift_u8(src_p->soh_l, 3u, 0x38u);
        break;

    case 2:
        dst_p[1] |= pack_left_shift_u8(src_p->mos_t_h, 0u, 0x07u);
        dst_p[1] |= pack_left_shift_u8(src_p->thermal_runaway, 3u, 0x38u);
        dst_p[6] |= pack_left_shift_u8(src_p->pch_failed, 7u, 0x80u);
        dst_p[7] |= pack_left_shift_u8(src_p->comm_off_chg_mos, 0u, 0x01u);
        dst_p[7] |= pack_left_shift_u8(src_p->comm_off_dsg_mos, 1u, 0x02u);
        dst_p[7] |= pack_left_shift_u8(src_p->key_off_chg_mos, 2u, 0x04u);
        dst_p[7] |= pack_left_shift_u8(src_p->key_off_dsg_mos, 3u, 0x08u);
        dst_p[7] |= pack_left_shift_u8(src_p->heat_st, 5u, 0x20u);
        dst_p[7] |= pack_left_shift_u8(src_p->limit_st, 6u, 0x40u);
        dst_p[7] |= pack_left_shift_u8(src_p->heat_error, 7u, 0x80u);
        break;

    default:
        break;
    }

    return (8);
}

int kms_dbc_real_time_part_fault_code_unpack(
    struct kms_dbc_real_time_part_fault_code_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fault_frame_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    switch (dst_p->fault_frame_id) {

    case 1:
        dst_p->cell_v_h = unpack_right_shift_u8(src_p[1], 0u, 0x07u);
        dst_p->cell_v_l = unpack_right_shift_u8(src_p[1], 3u, 0x38u);
        dst_p->detal_v_h = unpack_right_shift_u8(src_p[2], 0u, 0x07u);
        dst_p->cell_t_chg_h = unpack_right_shift_u8(src_p[2], 3u, 0x38u);
        dst_p->cell_t_chg_l = unpack_right_shift_u8(src_p[3], 0u, 0x07u);
        dst_p->cell_t_dsg_h = unpack_right_shift_u8(src_p[3], 3u, 0x38u);
        dst_p->cell_t_dsg_l = unpack_right_shift_u8(src_p[4], 0u, 0x07u);
        dst_p->detal_t_h = unpack_right_shift_u8(src_p[4], 3u, 0x38u);
        dst_p->sum_v_h = unpack_right_shift_u8(src_p[5], 0u, 0x07u);
        dst_p->sum_v_l = unpack_right_shift_u8(src_p[5], 3u, 0x38u);
        dst_p->short_protect = unpack_right_shift_u8(src_p[5], 6u, 0x40u);
        dst_p->cur_chg_h = unpack_right_shift_u8(src_p[6], 0u, 0x07u);
        dst_p->cur_dsg_h = unpack_right_shift_u8(src_p[6], 3u, 0x38u);
        dst_p->afe_pf_det_st = unpack_right_shift_u8(src_p[6], 6u, 0x40u);
        dst_p->soc_l = unpack_right_shift_u8(src_p[7], 0u, 0x07u);
        dst_p->soh_l = unpack_right_shift_u8(src_p[7], 3u, 0x38u);
        break;

    case 2:
        dst_p->mos_t_h = unpack_right_shift_u8(src_p[1], 0u, 0x07u);
        dst_p->thermal_runaway = unpack_right_shift_u8(src_p[1], 3u, 0x38u);
        dst_p->pch_failed = unpack_right_shift_u8(src_p[6], 7u, 0x80u);
        dst_p->comm_off_chg_mos = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
        dst_p->comm_off_dsg_mos = unpack_right_shift_u8(src_p[7], 1u, 0x02u);
        dst_p->key_off_chg_mos = unpack_right_shift_u8(src_p[7], 2u, 0x04u);
        dst_p->key_off_dsg_mos = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
        dst_p->heat_st = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
        dst_p->limit_st = unpack_right_shift_u8(src_p[7], 6u, 0x40u);
        dst_p->heat_error = unpack_right_shift_u8(src_p[7], 7u, 0x80u);
        break;

    default:
        break;
    }

    return (0);
}

int kms_dbc_real_time_part_fault_code_init(struct kms_dbc_real_time_part_fault_code_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_fault_code_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_fault_code_fault_frame_id_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_fault_frame_id_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_fault_frame_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_fault_code_mos_t_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_mos_t_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_mos_t_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_v_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_v_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_v_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_thermal_runaway_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_thermal_runaway_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_thermal_runaway_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_v_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_v_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_v_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_detal_v_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_detal_v_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_detal_v_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_t_chg_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_t_chg_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_t_chg_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_t_chg_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_t_chg_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_t_chg_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_t_dsg_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_t_dsg_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_t_dsg_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cell_t_dsg_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cell_t_dsg_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cell_t_dsg_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_detal_t_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_detal_t_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_detal_t_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_sum_v_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_sum_v_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_sum_v_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_sum_v_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_sum_v_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_sum_v_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_short_protect_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_short_protect_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_short_protect_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_cur_chg_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cur_chg_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cur_chg_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_cur_dsg_h_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_cur_dsg_h_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_cur_dsg_h_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_afe_pf_det_st_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_afe_pf_det_st_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_afe_pf_det_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_pch_failed_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_pch_failed_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_pch_failed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_comm_off_chg_mos_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_comm_off_chg_mos_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_comm_off_chg_mos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_soc_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_soc_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_soc_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_comm_off_dsg_mos_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_comm_off_dsg_mos_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_comm_off_dsg_mos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_key_off_chg_mos_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_key_off_chg_mos_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_key_off_chg_mos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_key_off_dsg_mos_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_key_off_dsg_mos_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_key_off_dsg_mos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_soh_l_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_soh_l_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_soh_l_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

uint8_t kms_dbc_real_time_part_fault_code_heat_st_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_heat_st_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_heat_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_limit_st_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_limit_st_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_limit_st_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t kms_dbc_real_time_part_fault_code_heat_error_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_fault_code_heat_error_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_fault_code_heat_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int kms_dbc_real_time_part_limit_cur_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_limit_cur_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->limit_cur_state, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->limic_cur, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->limic_cur, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->soh, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->soh, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->pwm_duty, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->pwm_duty, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_limit_cur_unpack(
    struct kms_dbc_real_time_part_limit_cur_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->limit_cur_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->limic_cur = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->limic_cur |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->soh = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->soh |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->pwm_duty = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->pwm_duty |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_limit_cur_init(struct kms_dbc_real_time_part_limit_cur_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_limit_cur_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_limit_cur_limit_cur_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_limit_cur_limit_cur_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_limit_cur_limit_cur_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_limit_cur_limic_cur_encode(double value)
{
    return (uint16_t)((value - -3000.0) / 0.1);
}

double kms_dbc_real_time_part_limit_cur_limic_cur_decode(uint16_t value)
{
    return (((double)value * 0.1) + -3000.0);
}

bool kms_dbc_real_time_part_limit_cur_limic_cur_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_limit_cur_soh_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double kms_dbc_real_time_part_limit_cur_soh_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool kms_dbc_real_time_part_limit_cur_soh_is_in_range(uint16_t value)
{
    return (value <= 2550u);
}

uint16_t kms_dbc_real_time_part_limit_cur_pwm_duty_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double kms_dbc_real_time_part_limit_cur_pwm_duty_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool kms_dbc_real_time_part_limit_cur_pwm_duty_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_calendar_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_calendar_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u8(src_p->year, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->month, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->day, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->hour, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->minute, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->second, 0u, 0xffu);

    return (6);
}

int kms_dbc_real_time_part_calendar_unpack(
    struct kms_dbc_real_time_part_calendar_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->year = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->month = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->day = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->hour = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->minute = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->second = unpack_right_shift_u8(src_p[5], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_calendar_init(struct kms_dbc_real_time_part_calendar_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_calendar_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_calendar_year_encode(double value)
{
    return (uint8_t)(value - 2000.0);
}

double kms_dbc_real_time_part_calendar_year_decode(uint8_t value)
{
    return ((double)value + 2000.0);
}

bool kms_dbc_real_time_part_calendar_year_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_calendar_month_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_calendar_month_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_calendar_month_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_calendar_day_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_calendar_day_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_calendar_day_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_calendar_hour_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_calendar_hour_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_calendar_hour_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_calendar_minute_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_calendar_minute_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_calendar_minute_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_calendar_second_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_calendar_second_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_calendar_second_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_charging_message_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_charging_message_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_right_shift_u16(src_p->rest_chg_time, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->rest_chg_time, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->wakeup_source, 0u, 0xffu);

    return (3);
}

int kms_dbc_real_time_part_charging_message_unpack(
    struct kms_dbc_real_time_part_charging_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->rest_chg_time = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->rest_chg_time |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->wakeup_source = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_charging_message_init(struct kms_dbc_real_time_part_charging_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_charging_message_t));

    return 0;
}

uint16_t kms_dbc_real_time_part_charging_message_rest_chg_time_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_charging_message_rest_chg_time_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_charging_message_rest_chg_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_charging_message_wakeup_source_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_charging_message_wakeup_source_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_charging_message_wakeup_source_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_bal_st_message_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_bal_st_message_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->balance_state, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->balance_cur, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->balance_cur, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->bal_batter_1to8, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->bal_batter_9to16, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->bal_batter_17to24, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->bal_batter_25to32, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_bal_st_message_unpack(
    struct kms_dbc_real_time_part_bal_st_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->balance_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->balance_cur = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->balance_cur |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->bal_batter_1to8 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->bal_batter_9to16 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->bal_batter_17to24 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->bal_batter_25to32 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_bal_st_message_init(struct kms_dbc_real_time_part_bal_st_message_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_bal_st_message_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_bal_st_message_balance_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_balance_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_balance_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_bal_st_message_balance_cur_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_balance_cur_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_balance_cur_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_bal_st_message_bal_batter_1to8_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_bal_batter_1to8_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_bal_batter_1to8_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_bal_st_message_bal_batter_9to16_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_bal_batter_9to16_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_bal_batter_9to16_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_bal_st_message_bal_batter_17to24_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_bal_batter_17to24_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_bal_batter_17to24_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_bal_st_message_bal_batter_25to32_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_bal_st_message_bal_batter_25to32_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_bal_st_message_bal_batter_25to32_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_status_message2_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_status_message2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->cell_number, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->ntc_number, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->remain_capacity, 24u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->remain_capacity, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->remain_capacity, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u32(src_p->remain_capacity, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->cycle_time, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->cycle_time, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_status_message2_unpack(
    struct kms_dbc_real_time_part_status_message2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_number = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->ntc_number = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->remain_capacity = unpack_left_shift_u32(src_p[2], 24u, 0xffu);
    dst_p->remain_capacity |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->remain_capacity |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->remain_capacity |= unpack_right_shift_u32(src_p[5], 0u, 0xffu);
    dst_p->cycle_time = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->cycle_time |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_status_message2_init(struct kms_dbc_real_time_part_status_message2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_status_message2_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_status_message2_cell_number_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message2_cell_number_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message2_cell_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message2_ntc_number_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message2_ntc_number_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message2_ntc_number_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint32_t kms_dbc_real_time_part_status_message2_remain_capacity_encode(double value)
{
    return (uint32_t)(value);
}

double kms_dbc_real_time_part_status_message2_remain_capacity_decode(uint32_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message2_remain_capacity_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_status_message2_cycle_time_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_status_message2_cycle_time_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message2_cycle_time_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_status_message1_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_status_message1_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->bat_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->chg_detect, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->loard_detect, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->do_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->di_state, 0u, 0xffu);

    return (5);
}

int kms_dbc_real_time_part_status_message1_unpack(
    struct kms_dbc_real_time_part_status_message1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->bat_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->chg_detect = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->loard_detect = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->do_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->di_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_status_message1_init(struct kms_dbc_real_time_part_status_message1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_status_message1_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_status_message1_bat_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message1_bat_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message1_bat_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message1_chg_detect_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message1_chg_detect_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message1_chg_detect_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message1_loard_detect_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message1_loard_detect_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message1_loard_detect_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message1_do_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message1_do_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message1_do_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message1_di_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message1_di_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message1_di_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_status_message0_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_status_message0_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->chg_mos_state, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->dis_chg_mos_state, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->pre_mos_state, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->heat_mos_state, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->fan_mos_state, 0u, 0xffu);

    return (5);
}

int kms_dbc_real_time_part_status_message0_unpack(
    struct kms_dbc_real_time_part_status_message0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->chg_mos_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->dis_chg_mos_state = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->pre_mos_state = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->heat_mos_state = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->fan_mos_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_status_message0_init(struct kms_dbc_real_time_part_status_message0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_status_message0_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_status_message0_chg_mos_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message0_chg_mos_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message0_chg_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message0_dis_chg_mos_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message0_dis_chg_mos_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message0_dis_chg_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message0_pre_mos_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message0_pre_mos_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message0_pre_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message0_heat_mos_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message0_heat_mos_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message0_heat_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_status_message0_fan_mos_state_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_status_message0_fan_mos_state_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_status_message0_fan_mos_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_temp_statistics_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_temp_statistics_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 5);

    dst_p[0] |= pack_left_shift_u8(src_p->max_t, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->max_t_no, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->min_t, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->min_t_no, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->diff_t, 0u, 0xffu);

    return (5);
}

int kms_dbc_real_time_part_temp_statistics_unpack(
    struct kms_dbc_real_time_part_temp_statistics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 5u) {
        return (-EINVAL);
    }

    dst_p->max_t = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->max_t_no = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->min_t = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->min_t_no = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->diff_t = unpack_right_shift_u8(src_p[4], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_temp_statistics_init(struct kms_dbc_real_time_part_temp_statistics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_temp_statistics_t));

    return 0;
}

uint8_t kms_dbc_real_time_part_temp_statistics_max_t_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double kms_dbc_real_time_part_temp_statistics_max_t_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_temp_statistics_max_t_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_temp_statistics_max_t_no_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_temp_statistics_max_t_no_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_temp_statistics_max_t_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_temp_statistics_min_t_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double kms_dbc_real_time_part_temp_statistics_min_t_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_temp_statistics_min_t_is_in_range(uint8_t value)
{
    return (value >= 40u);
}

uint8_t kms_dbc_real_time_part_temp_statistics_min_t_no_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_temp_statistics_min_t_no_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_temp_statistics_min_t_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t kms_dbc_real_time_part_temp_statistics_diff_t_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_temp_statistics_diff_t_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_temp_statistics_diff_t_is_in_range(uint8_t value)
{
    return (value <= 215u);
}

int kms_dbc_real_time_part_volt_statistics_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_volt_statistics_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->max_v, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->max_v, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->max_v_no, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->min_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->min_v, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->min_no, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->diff_v, 8u, 0xffu);
    dst_p[7] |= pack_left_shift_u16(src_p->diff_v, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_volt_statistics_unpack(
    struct kms_dbc_real_time_part_volt_statistics_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->max_v = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->max_v |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->max_v_no = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->min_v = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->min_v |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->min_no = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->diff_v = unpack_left_shift_u16(src_p[6], 8u, 0xffu);
    dst_p->diff_v |= unpack_right_shift_u16(src_p[7], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_volt_statistics_init(struct kms_dbc_real_time_part_volt_statistics_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_volt_statistics_t));

    return 0;
}

uint16_t kms_dbc_real_time_part_volt_statistics_max_v_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_volt_statistics_max_v_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_volt_statistics_max_v_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint8_t kms_dbc_real_time_part_volt_statistics_max_v_no_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_volt_statistics_max_v_no_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_volt_statistics_max_v_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_volt_statistics_min_v_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_volt_statistics_min_v_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_volt_statistics_min_v_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint8_t kms_dbc_real_time_part_volt_statistics_min_no_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_volt_statistics_min_no_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_volt_statistics_min_no_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_volt_statistics_diff_v_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_volt_statistics_diff_v_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_volt_statistics_diff_v_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

int kms_dbc_real_time_part_cell_temp_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_cell_temp_t *src_p,
    size_t size)
{
    uint8_t cell_temp_frame_id;
    uint8_t temper1;
    uint8_t temper2;
    uint8_t temper3;
    uint8_t temper4;
    uint8_t temper5;
    uint8_t temper6;
    uint8_t temper7;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    cell_temp_frame_id = (uint8_t)src_p->cell_temp_frame_id;
    dst_p[0] |= pack_left_shift_u8(cell_temp_frame_id, 0u, 0xffu);

    switch (src_p->cell_temp_frame_id) {

    case 1:
        temper1 = (uint8_t)src_p->temper1;
        dst_p[1] |= pack_left_shift_u8(temper1, 0u, 0xffu);
        temper2 = (uint8_t)src_p->temper2;
        dst_p[2] |= pack_left_shift_u8(temper2, 0u, 0xffu);
        temper3 = (uint8_t)src_p->temper3;
        dst_p[3] |= pack_left_shift_u8(temper3, 0u, 0xffu);
        temper4 = (uint8_t)src_p->temper4;
        dst_p[4] |= pack_left_shift_u8(temper4, 0u, 0xffu);
        temper5 = (uint8_t)src_p->temper5;
        dst_p[5] |= pack_left_shift_u8(temper5, 0u, 0xffu);
        temper6 = (uint8_t)src_p->temper6;
        dst_p[6] |= pack_left_shift_u8(temper6, 0u, 0xffu);
        temper7 = (uint8_t)src_p->temper7;
        dst_p[7] |= pack_left_shift_u8(temper7, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int kms_dbc_real_time_part_cell_temp_unpack(
    struct kms_dbc_real_time_part_cell_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t cell_temp_frame_id;
    uint8_t temper1;
    uint8_t temper2;
    uint8_t temper3;
    uint8_t temper4;
    uint8_t temper5;
    uint8_t temper6;
    uint8_t temper7;

    if (size < 8u) {
        return (-EINVAL);
    }

    cell_temp_frame_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cell_temp_frame_id = (int8_t)cell_temp_frame_id;

    switch (dst_p->cell_temp_frame_id) {

    case 1:
        temper1 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
        dst_p->temper1 = (int8_t)temper1;
        temper2 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
        dst_p->temper2 = (int8_t)temper2;
        temper3 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
        dst_p->temper3 = (int8_t)temper3;
        temper4 = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
        dst_p->temper4 = (int8_t)temper4;
        temper5 = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
        dst_p->temper5 = (int8_t)temper5;
        temper6 = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
        dst_p->temper6 = (int8_t)temper6;
        temper7 = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
        dst_p->temper7 = (int8_t)temper7;
        break;

    default:
        break;
    }

    return (0);
}

int kms_dbc_real_time_part_cell_temp_init(struct kms_dbc_real_time_part_cell_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_cell_temp_t));

    return 0;
}

int8_t kms_dbc_real_time_part_cell_temp_cell_temp_frame_id_encode(double value)
{
    return (int8_t)(value);
}

double kms_dbc_real_time_part_cell_temp_cell_temp_frame_id_decode(int8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_temp_cell_temp_frame_id_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper1_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper1_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper1_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper2_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper2_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper2_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper3_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper3_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper3_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper4_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper4_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper4_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper5_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper5_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper5_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper6_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper6_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper6_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_cell_temp_temper7_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double kms_dbc_real_time_part_cell_temp_temper7_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_cell_temp_temper7_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_cell_volt_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_cell_volt_t *src_p,
    size_t size)
{
    uint16_t volt10;
    uint16_t volt11;
    uint16_t volt12;
    uint16_t volt13;
    uint16_t volt14;
    uint16_t volt15;
    uint16_t volt16;
    uint16_t volt17;
    uint16_t volt18;
    uint16_t volt19;
    uint16_t volt1;
    uint16_t volt20;
    uint16_t volt21;
    uint16_t volt22;
    uint16_t volt23;
    uint16_t volt24;
    uint16_t volt2;
    uint16_t volt3;
    uint16_t volt4;
    uint16_t volt5;
    uint16_t volt6;
    uint16_t volt7;
    uint16_t volt8;
    uint16_t volt9;
    uint8_t cell_volt_frame_id;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    cell_volt_frame_id = (uint8_t)src_p->cell_volt_frame_id;
    dst_p[0] |= pack_left_shift_u8(cell_volt_frame_id, 0u, 0xffu);

    switch (src_p->cell_volt_frame_id) {

    case 1:
        volt1 = (uint16_t)src_p->volt1;
        dst_p[1] |= pack_right_shift_u16(volt1, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt1, 0u, 0xffu);
        volt2 = (uint16_t)src_p->volt2;
        dst_p[3] |= pack_right_shift_u16(volt2, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt2, 0u, 0xffu);
        volt3 = (uint16_t)src_p->volt3;
        dst_p[5] |= pack_right_shift_u16(volt3, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt3, 0u, 0xffu);
        break;

    case 2:
        volt4 = (uint16_t)src_p->volt4;
        dst_p[1] |= pack_right_shift_u16(volt4, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt4, 0u, 0xffu);
        volt5 = (uint16_t)src_p->volt5;
        dst_p[3] |= pack_right_shift_u16(volt5, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt5, 0u, 0xffu);
        volt6 = (uint16_t)src_p->volt6;
        dst_p[5] |= pack_right_shift_u16(volt6, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt6, 0u, 0xffu);
        break;

    case 3:
        volt7 = (uint16_t)src_p->volt7;
        dst_p[1] |= pack_right_shift_u16(volt7, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt7, 0u, 0xffu);
        volt8 = (uint16_t)src_p->volt8;
        dst_p[3] |= pack_right_shift_u16(volt8, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt8, 0u, 0xffu);
        volt9 = (uint16_t)src_p->volt9;
        dst_p[5] |= pack_right_shift_u16(volt9, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt9, 0u, 0xffu);
        break;

    case 4:
        volt10 = (uint16_t)src_p->volt10;
        dst_p[1] |= pack_right_shift_u16(volt10, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt10, 0u, 0xffu);
        volt11 = (uint16_t)src_p->volt11;
        dst_p[3] |= pack_right_shift_u16(volt11, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt11, 0u, 0xffu);
        volt12 = (uint16_t)src_p->volt12;
        dst_p[5] |= pack_right_shift_u16(volt12, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt12, 0u, 0xffu);
        break;

    case 5:
        volt13 = (uint16_t)src_p->volt13;
        dst_p[1] |= pack_right_shift_u16(volt13, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt13, 0u, 0xffu);
        volt14 = (uint16_t)src_p->volt14;
        dst_p[3] |= pack_right_shift_u16(volt14, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt14, 0u, 0xffu);
        volt15 = (uint16_t)src_p->volt15;
        dst_p[5] |= pack_right_shift_u16(volt15, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt15, 0u, 0xffu);
        break;

    case 6:
        volt16 = (uint16_t)src_p->volt16;
        dst_p[1] |= pack_right_shift_u16(volt16, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt16, 0u, 0xffu);
        volt17 = (uint16_t)src_p->volt17;
        dst_p[3] |= pack_right_shift_u16(volt17, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt17, 0u, 0xffu);
        volt18 = (uint16_t)src_p->volt18;
        dst_p[5] |= pack_right_shift_u16(volt18, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt18, 0u, 0xffu);
        break;

    case 7:
        volt19 = (uint16_t)src_p->volt19;
        dst_p[1] |= pack_right_shift_u16(volt19, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt19, 0u, 0xffu);
        volt20 = (uint16_t)src_p->volt20;
        dst_p[3] |= pack_right_shift_u16(volt20, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt20, 0u, 0xffu);
        volt21 = (uint16_t)src_p->volt21;
        dst_p[5] |= pack_right_shift_u16(volt21, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt21, 0u, 0xffu);
        break;

    case 8:
        volt22 = (uint16_t)src_p->volt22;
        dst_p[1] |= pack_right_shift_u16(volt22, 8u, 0xffu);
        dst_p[2] |= pack_left_shift_u16(volt22, 0u, 0xffu);
        volt23 = (uint16_t)src_p->volt23;
        dst_p[3] |= pack_right_shift_u16(volt23, 8u, 0xffu);
        dst_p[4] |= pack_left_shift_u16(volt23, 0u, 0xffu);
        volt24 = (uint16_t)src_p->volt24;
        dst_p[5] |= pack_right_shift_u16(volt24, 8u, 0xffu);
        dst_p[6] |= pack_left_shift_u16(volt24, 0u, 0xffu);
        break;

    default:
        break;
    }

    return (8);
}

int kms_dbc_real_time_part_cell_volt_unpack(
    struct kms_dbc_real_time_part_cell_volt_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t volt10;
    uint16_t volt11;
    uint16_t volt12;
    uint16_t volt13;
    uint16_t volt14;
    uint16_t volt15;
    uint16_t volt16;
    uint16_t volt17;
    uint16_t volt18;
    uint16_t volt19;
    uint16_t volt1;
    uint16_t volt20;
    uint16_t volt21;
    uint16_t volt22;
    uint16_t volt23;
    uint16_t volt24;
    uint16_t volt2;
    uint16_t volt3;
    uint16_t volt4;
    uint16_t volt5;
    uint16_t volt6;
    uint16_t volt7;
    uint16_t volt8;
    uint16_t volt9;
    uint8_t cell_volt_frame_id;

    if (size < 8u) {
        return (-EINVAL);
    }

    cell_volt_frame_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->cell_volt_frame_id = (int8_t)cell_volt_frame_id;

    switch (dst_p->cell_volt_frame_id) {

    case 1:
        volt1 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt1 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt1 = (int16_t)volt1;
        volt2 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt2 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt2 = (int16_t)volt2;
        volt3 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt3 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt3 = (int16_t)volt3;
        break;

    case 2:
        volt4 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt4 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt4 = (int16_t)volt4;
        volt5 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt5 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt5 = (int16_t)volt5;
        volt6 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt6 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt6 = (int16_t)volt6;
        break;

    case 3:
        volt7 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt7 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt7 = (int16_t)volt7;
        volt8 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt8 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt8 = (int16_t)volt8;
        volt9 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt9 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt9 = (int16_t)volt9;
        break;

    case 4:
        volt10 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt10 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt10 = (int16_t)volt10;
        volt11 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt11 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt11 = (int16_t)volt11;
        volt12 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt12 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt12 = (int16_t)volt12;
        break;

    case 5:
        volt13 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt13 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt13 = (int16_t)volt13;
        volt14 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt14 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt14 = (int16_t)volt14;
        volt15 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt15 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt15 = (int16_t)volt15;
        break;

    case 6:
        volt16 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt16 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt16 = (int16_t)volt16;
        volt17 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt17 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt17 = (int16_t)volt17;
        volt18 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt18 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt18 = (int16_t)volt18;
        break;

    case 7:
        volt19 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt19 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt19 = (int16_t)volt19;
        volt20 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt20 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt20 = (int16_t)volt20;
        volt21 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt21 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt21 = (int16_t)volt21;
        break;

    case 8:
        volt22 = unpack_left_shift_u16(src_p[1], 8u, 0xffu);
        volt22 |= unpack_right_shift_u16(src_p[2], 0u, 0xffu);
        dst_p->volt22 = (int16_t)volt22;
        volt23 = unpack_left_shift_u16(src_p[3], 8u, 0xffu);
        volt23 |= unpack_right_shift_u16(src_p[4], 0u, 0xffu);
        dst_p->volt23 = (int16_t)volt23;
        volt24 = unpack_left_shift_u16(src_p[5], 8u, 0xffu);
        volt24 |= unpack_right_shift_u16(src_p[6], 0u, 0xffu);
        dst_p->volt24 = (int16_t)volt24;
        break;

    default:
        break;
    }

    return (0);
}

int kms_dbc_real_time_part_cell_volt_init(struct kms_dbc_real_time_part_cell_volt_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_cell_volt_t));

    return 0;
}

int8_t kms_dbc_real_time_part_cell_volt_cell_volt_frame_id_encode(double value)
{
    return (int8_t)(value);
}

double kms_dbc_real_time_part_cell_volt_cell_volt_frame_id_decode(int8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_cell_volt_frame_id_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt7_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt7_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt7_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt22_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt22_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt22_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt19_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt19_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt19_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt16_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt16_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt16_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt13_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt13_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt13_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt10_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt10_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt10_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt4_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt4_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt4_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt1_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt1_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt1_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt8_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt8_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt8_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt5_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt5_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt5_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt23_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt23_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt23_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt20_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt20_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt20_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt17_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt17_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt17_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt14_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt14_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt14_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt11_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt11_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt11_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt2_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt2_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt2_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt9_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt9_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt9_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt6_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt6_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt6_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt24_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt24_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt24_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt21_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt21_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt21_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt18_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt18_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt18_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt15_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt15_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt15_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt12_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt12_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt12_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t kms_dbc_real_time_part_cell_volt_volt3_encode(double value)
{
    return (int16_t)(value);
}

double kms_dbc_real_time_part_cell_volt_volt3_decode(int16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_cell_volt_volt3_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_batter_sum_singal1_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_batter_sum_singal1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_right_shift_u16(src_p->power, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->power, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->total_energy, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->total_energy, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mos_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->board_temp, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->heat_temp, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->heat_cur, 0u, 0xffu);

    return (8);
}

int kms_dbc_real_time_part_batter_sum_singal1_unpack(
    struct kms_dbc_real_time_part_batter_sum_singal1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->power = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->power |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->total_energy = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->total_energy |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->mos_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->board_temp = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->heat_temp = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->heat_cur = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int kms_dbc_real_time_part_batter_sum_singal1_init(struct kms_dbc_real_time_part_batter_sum_singal1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_batter_sum_singal1_t));

    return 0;
}

uint16_t kms_dbc_real_time_part_batter_sum_singal1_power_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_batter_sum_singal1_power_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_batter_sum_singal1_power_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_batter_sum_singal1_total_energy_encode(double value)
{
    return (uint16_t)(value);
}

double kms_dbc_real_time_part_batter_sum_singal1_total_energy_decode(uint16_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_batter_sum_singal1_total_energy_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint8_t kms_dbc_real_time_part_batter_sum_singal1_mos_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double kms_dbc_real_time_part_batter_sum_singal1_mos_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_batter_sum_singal1_mos_temp_is_in_range(uint8_t value)
{
    return (value >= 40u);
}

uint8_t kms_dbc_real_time_part_batter_sum_singal1_board_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double kms_dbc_real_time_part_batter_sum_singal1_board_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_batter_sum_singal1_board_temp_is_in_range(uint8_t value)
{
    return (value >= 40u);
}

uint8_t kms_dbc_real_time_part_batter_sum_singal1_heat_temp_encode(double value)
{
    return (uint8_t)(value - -40.0);
}

double kms_dbc_real_time_part_batter_sum_singal1_heat_temp_decode(uint8_t value)
{
    return ((double)value + -40.0);
}

bool kms_dbc_real_time_part_batter_sum_singal1_heat_temp_is_in_range(uint8_t value)
{
    return (value >= 40u);
}

uint8_t kms_dbc_real_time_part_batter_sum_singal1_heat_cur_encode(double value)
{
    return (uint8_t)(value);
}

double kms_dbc_real_time_part_batter_sum_singal1_heat_cur_decode(uint8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_batter_sum_singal1_heat_cur_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int kms_dbc_real_time_part_batter_sum_singal0_pack(
    uint8_t *dst_p,
    const struct kms_dbc_real_time_part_batter_sum_singal0_t *src_p,
    size_t size)
{
    uint8_t life;

    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_right_shift_u16(src_p->sum_v, 8u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->sum_v, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->cur, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->cur, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->soc, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->soc, 0u, 0xffu);
    life = (uint8_t)src_p->life;
    dst_p[6] |= pack_left_shift_u8(life, 0u, 0xffu);

    return (7);
}

int kms_dbc_real_time_part_batter_sum_singal0_unpack(
    struct kms_dbc_real_time_part_batter_sum_singal0_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t life;

    if (size < 7u) {
        return (-EINVAL);
    }

    dst_p->sum_v = unpack_left_shift_u16(src_p[0], 8u, 0xffu);
    dst_p->sum_v |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->cur = unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->cur |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->soc = unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->soc |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    life = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->life = (int8_t)life;

    return (0);
}

int kms_dbc_real_time_part_batter_sum_singal0_init(struct kms_dbc_real_time_part_batter_sum_singal0_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct kms_dbc_real_time_part_batter_sum_singal0_t));

    return 0;
}

uint16_t kms_dbc_real_time_part_batter_sum_singal0_sum_v_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double kms_dbc_real_time_part_batter_sum_singal0_sum_v_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool kms_dbc_real_time_part_batter_sum_singal0_sum_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t kms_dbc_real_time_part_batter_sum_singal0_cur_encode(double value)
{
    return (uint16_t)((value - -3000.0) / 0.1);
}

double kms_dbc_real_time_part_batter_sum_singal0_cur_decode(uint16_t value)
{
    return (((double)value * 0.1) + -3000.0);
}

bool kms_dbc_real_time_part_batter_sum_singal0_cur_is_in_range(uint16_t value)
{
    return (value <= 255u);
}

uint16_t kms_dbc_real_time_part_batter_sum_singal0_soc_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double kms_dbc_real_time_part_batter_sum_singal0_soc_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool kms_dbc_real_time_part_batter_sum_singal0_soc_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int8_t kms_dbc_real_time_part_batter_sum_singal0_life_encode(double value)
{
    return (int8_t)(value);
}

double kms_dbc_real_time_part_batter_sum_singal0_life_decode(int8_t value)
{
    return ((double)value);
}

bool kms_dbc_real_time_part_batter_sum_singal0_life_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}
